name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@866b3755ea5ffb1348b6418105b09b614ac3cf89
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
